### ISSUE TITLE
BTP Standard: Other Network <> Other Network Direct Communication

### ISSUE THREAD

**Issue by BennyOptions** [icon-project/btp#19]
We must find a scalable standard to allow non-ICON networks to communicate directly with each other. Here is one initial plan to get the discussion going:

All BTP messages from Other Networks arrive to the ICON BMC, then ICON BMC can emit events for BMR to relay message to correct destination chain. This way, each Other Network only needs one BMV, but ICON Network will have BMV of all connected networks. But from a User Experience point, it is still Other Network <> Other Network directly. 

Example:

Bob’s goal -> Send 1 ACALA token from Acala network to Binance Smart Chain

1.) Bob sends 1 ACALA token to acala_BSH
2.) acala_BSH creates this btpMessage (src: ACALA, dst: BSC, svc: tokenTransfer, sn: 1, msg: Bytes)
3.) btpMessage is sent to acala_BMC
4.) BMR reads event from acala_BMC
5.) BMR sends btpMessage to icon_BMC
6.) icon_BMV verifies btpMessage data
7.) icon_BMC emits an event of verified btpMessage
8.) BMR reads event from icon_BMC
9.) BMR sends btpMessage to bsc_BMC (this is because dst = BSC)
10.) bsc_BMC sends the btpMessage to bsc_BMV
11.) bsc_BMV verifies btpMessage
12.) bsc_BMC sends message proof to bsc_BSH
13. bsc_BSH mints 1 ACALA token

**Comment by unamed12** [comment]
Hey, thank you for your suggestion. Based on your idea, we did some research and come up with this logic. Please check this and add comments on this doc or this thread. 

https://docs.google.com/document/d/1KlKqxzvLRVqsud3ds38mjvHgLHbXaagEZYLYMMn5i58/edit?usp=sharing

Thanks!

**Comment by BennyOptions** [comment]
@unamed12 thanks for sharing this. My primary concern is about the time that the GatherFee method is called. We are using off-chain job to trigger GatherFee method. Instead, I propose that GatherFee is called on every transaction (or most) in a BSH. The BSH standard should include "piggy-backing" GatherFee calls on other transactions. This way, GatherFee is more scalable. If there are 100 BSH on one network, GatherFee method must be called by BMC on all 100 contracts when ICON BMC calls this method.

I suggest instead that each BSH be responsible for calling its own GatherFee method each time there is a transaction on that BSH.

**Comment by BennyOptions** [comment]
This issue has been resolved with a new BSH contract standard
