### ISSUE TITLE
Add support for Keccak256 to JavaScore Crypto and Context API

### ISSUE THREAD

**Issue by mohamedelshami** [icon-project/btp#44]
Keccak256 is required to verify the Etheruem block header in the JavaScore verifier contract.

This needs to be available in the Context API and relevant SDK implementation

https://github.com/icon-project/goloop/blob/master/javaee/api/src/java/score/Context.java

**Comment by leeheonseung** [comment]
> Keccak256 is required to verify the Etheruem block header in the JavaScore verifier contract.
> 
> This needs to be available in the Context API and relevant SDK implementation
> 
> https://github.com/icon-project/goloop/blob/master/javaee/api/src/java/score/Context.java

got it.
we have plan to support keccak256 in next week

**Comment by sink772** [comment]
Added in https://github.com/icon-project/goloop/commit/5e62fc674debaa679c25f1712f4ae890ce21dd54
